---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tyk-redis
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters
  prune: true
  retryInterval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-redis
  targetNamespace: tyk-redis
  timeout: 4m0s
  wait: true
