---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: tyk-redis
  namespace: flux-system
spec:
  interval: 1m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    semver: ">= 6.2.14"
    
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tyk-redis
  namespace: flux-system
spec:
  releaseName: tyk-redis
  timeout: 1m0s
  chartRef:
    kind: OCIRepository
    name: tyk-redis
    namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  targetNamespace: tyk-oss
  interval: 1m0s
  values:
    replicaCount: 4   
    resources:
      requests:
        memory: "256Mi"   
        cpu: "100m"       
      limits:
        memory: "512Mi"     
        cpu: "200m"
